sudo: false
dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
matrix:
  include:
    - python: '3.8'
      env: BLACK=1
env:
  matrix:
    - DJANGO_VERSION='>=1.11,<1.12'
    - DJANGO_VERSION='>=2.1,<2.2'
    - DJANGO_VERSION='>=2.2,<2.3'
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
install:
  - pip install --upgrade pip
  - pip install -e .[development]
  - "pip install Django$DJANGO_VERSION"
script:
  - coverage run --source=uk_geo_utils --omit=uk_geo_utils/tests/*.py,uk_geo_utils/migrations/*.py,uk_geo_utils/fixtures/*.py run_tests.py
  - sh -c "if [ '$BLACK' = '1' ]; then pip install black ; fi"
  - sh -c "if [ '$BLACK' = '1' ]; then black --check . ; fi"
after_success:
  - coveralls
