version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install Tox
          command: pip install -U pip tox
      - run:
          command: tox
          name: Run tests
      - python/save-cache

workflows:
  main:
    jobs:
      - build-and-test
