version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.2
        environment:
          CIRCLECI: true
          PGHOST: 127.0.0.1
      - image: circleci/postgres:11.2-alpine-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -U pip tox
            sudo apt-get update && sudo apt-get install -y gdal-bin python3-gdal
      - run:
          command: tox
          name: Run tests

workflows:
  main:
    jobs:
      - build-and-test
