site_name: Django UK Geo Utils
pages:
    - Home: index.md
    - Installation: installation.md
    - Importing Data: importing_data.md
    - Geocoders: geocoders.md
    - Extending the models: extending.md
    - Licensing: licence.md
theme: readthedocs
